### PR TITLE
Feature 239 - Sort By made darker color and added an arrow

### PR DESCRIPTION
**Pull request by brianandres2**
-Made 'Sort By ____' slightly darker 
-Added a drop-down arrow to 'Relevance' - arrow only shows when 'Relevance'  is the selected term

Original: 

Screen Shot 2022-08-09 at 2 18 13 PM

Changes:

Screen Shot 2022-08-09 at 2 17 09 PM

### CODE REVIEW

**Comment by paulpilone** [comment]
Technically looks good. @paulineobps is this acceptable? If @brianandres2 attached a screenshot of Relevance. If you select something else (e.g. Author) it looks like this:
image

**Comment by paulineobps** [comment]
checking on dev image looks like this image and full dropdown appears when hover
image

**Comment by paulpilone** [comment]
@paulineobps Just a heads up: this is a PR so by closing this we can't merge this change in.

If Brian's change looks acceptable I'll merge this in and schedule it for deployment. This is not on develop yet.

**Comment by paulineobps** [comment]
so I cannot see  what Brian has done on dev - sorry.    fine to go ahead.

 Additional comment for SORT BY **ENDORSED**  - asc and desc what element is it sorting on?

**Comment by paulpilone** [comment]
For the ENDORSED filter we filter by:

`obps_endorsementExternal_externalEndorsedBy.keyword:asc` (Ascending)
`obps_endorsementExternal_externalEndorsedBy.keyword:desc` (Descending)

**Comment by paulineobps** [comment]
sorry - Just need to be able to explain this;  the difference is not obvious (other than year order)
this is ENDORSED asc 
image
this is ENDORSED desc
image

**Comment by paulpilone** [comment]
@paulineobps We can continue that discussion in an Issue. This PR will be marked as done and closed since it's just about the styling of the button.

**Review by paulpilone — APPROVED** [review]

**Pull request merged**
