### PR TITLE
Adding modal for terminology descriptions

### PR DESCRIPTION
**Pull request by justinykuo**
Based on https://github.com/iodepo/OceanBestPractices/issues/20.

This PR adds a modal to the terminologies modal.

[Terminologies Modal.mov.zip](https://github.com/iodepo/OceanBestPractices/files/3970578/Terminologies.Modal.mov.zip)

### CODE REVIEW

**Comment by pbuttigieg** [comment]
Looks good @justinykuo - can the text be condensed a bit? wrapped at a sensible number of characters so we don't have stringy lines?

**Comment by justinykuo** [comment]
Hey @pbuttigieg , this is the narrower text. Let me know what you think:

[Terminology Condensed Text Recording.mov.zip](https://github.com/iodepo/OceanBestPractices/files/3974176/Terminology.Condensed.Text.Recording.mov.zip)

**Comment by pbuttigieg** [comment]
Looks better, @justinykuo 

This makes me think the better thing to do is actually make the bounding boxes narrower (horizontally) and have the text wrapped dynamically. 

The goal is to make it easier to read so the eye doesn't have to traverse the whole screen. Something like the size of a GitHub comment box I'm typing in now would be good.

**Comment by justinykuo** [comment]
Hey @pbuttigieg,

I've added a mechanism by which the modal width can be adjusted when rendered in the app. This doesn't affect previously written code, but can be used in the future.

[Modal Width Mechanism.mov.zip](https://github.com/iodepo/OceanBestPractices/files/4003227/Modal.Width.Mechanism.mov.zip)

**Pull request merged**
