### PR TITLE
184 - Adds english analyzer to text fields for stemming

### LINKED ISSUE #184: Search is not matching plural versions of a search field.
From the bug report:

I searched for transmissometer expecting to pick up 'Best Practices for Shipboard Underway Transmissometers. Version ONE.'  I searched in Title and All Fields but it did not find it - but does if I search for transmissometers

### PR DESCRIPTION
**Pull request by paulpilone**
Closes #184

### CODE REVIEW

**Comment by paulpilone** [comment]
@paulineobps I've fixed this issue by adding the "english" analyzer to specific fields in Elasticsearch. What this does is provide "stemming" for each word in the field which should improve searches for things like plural or possessive fields. e.g. I wrote tests that now find a title with "ocean" when you search for "oceans" or "body" when you search for "bodies".

I've added this analyzer to the following fields for now (seemed most appropriate to me):
- dc_title
- dc_title_alternative
- bitstreamsText (the actual document text extracted from the PDF)
- dc_abstract
- dc_description_notes

If there are other fields you'd like to see this added to please let me know and I can evaluate the level of difficulty for that.

**Comment by paulineobps** [comment]
Thanks Paul

The most important search for stemming to be applied is ALL FIELDS - possible?

Pauline
Pauline SIMPSON
Ocean Best Practices System Project Manager
https://www.oceanbestpractices.org/

UNESCO /IOC Project Office for IODE, Wandelaarkaai 7/61, 8400 Oostende, Belgium
Email: ***@***.******@***.***>;   Alternate email: ***@***.******@***.***>; Skype: Pauline Simpson
ORCID: 0000-0003-2551-5740


<http://www.iode.org>


________________________________

**Comment by paulpilone** [comment]
@paulineobps Sorry my message probably wasn't very clear. I added the english analyzer to those fields in the Elasticsearch index meaning those fields will be indexed with stemming enabled. When we search "All Fields" we search those fields - so we get the stemming.

"All Fields" is no different than scoping a search to a specific field - it's just that it includes _all_ of the fields when doing the search.

**Comment by paulineobps** [comment]
I think you know this Paul but just confirming, whatever I try for the singular/plural search does not work

**Comment by paulpilone** [comment]
@paulineobps I commented in #184 that it's deployed but I haven't re-indexed documents yet which will be required in order to pick up this change.

**Pull request merged**
